name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name ${NAME}
          git config --global user.email ${EMAIL}
          # Pass the --rebase-merges option to git rebase by default
          git config --global pull.rebase merges
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          # Add the repo which you forked to the remote and name it as "upstream"
          git remote add upstream ${REPO_FORK}
          # Fetch the upstream branches to local
          git fetch upstream
          # Merge changes
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
        # Change the below to your settings
        env:
          NAME: eighty88
          EMAIL: 49605393+eighty88@users.noreply.github.com
          REPO_FORK: https://github.com/eighty88/Find_The_Assassin.git
